name: "Publish to Hex"
inputs:
  key:
    description: "Write key"
    required: true
  organization:
    description: "Optional organization to deploy package into"
    required: false
  name:
    description: "Name of package"
    required: true
  working-directory:
    description: "Working directory to Mix project"
    default: "."
outputs:
  local-version:
    description: "Version from project"
    value: ${{ steps.local-version.outputs.VERSION }}
  remote-version:
    description: "Version published to hex"
    value: ${{ steps.remote-version.outputs.VERSION }}
runs:
  using: "composite"
  steps:
    - name: Authenticate
      shell: bash
      run: |
        echo "::group::Auth"
        echo "Authenticating"
        echo "::endgroup::"
        mix hex.config api_key ${{ inputs.key }}

    - name: Find local version
      id: local-version
      shell: bash
      working_directory: ${{ inputs.working-directory }}
      run: |
        name=${{ inputs.name }}
        version=$(grep "@version \"" mix.exs | cut -d "\"" -f 2)

        echo "::group::Local version"
        echo "${version}"
        echo "::endgroup::"
        echo "::set-output name=VERSION::$(echo $version)"

    - name: Find remote version
      id: remote-version
      shell: bash
      working_directory: ${{ inputs.working-directory }}
      run: |
        name=${{ inputs.name }}
        organization=${{ inputs.organization }}

        if [[ -n "${organization}" ]]; then
          search=$(mix hex.search "${name}" --organization "${organization}")
          remote_version=$(echo "${search}" | grep -E "${.organization} +${name} " | awk 'BEGIN {FS="  [ ]+"}{print $3}')
        else
          search=$(mix hex.search "${name}" | sed 's/\x1b\[[^m]+m//g;')

          if echo $search | head -n 1 | grep -q "^Organization"; then
            remote_version=$(echo "${search}" | grep -E "\\w+ +${name} " | awk 'BEGIN {FS="  [ ]+"}{print $4}')
          else
            remote_version=$(echo "${search}" | grep -E "^${name} " | awk 'BEGIN {FS="  [ ]+"}{print $3}')
          fi
        fi

        echo "::group::Remote version"
        echo "${remote_version}"
        echo "::endgroup::"
        echo "::set-output name=VERSION::$(echo $remote_version)"

    - name: Verify versions
      shell: bash
      working_directory: ${{ inputs.working-directory }}
      run: |
        SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"

        echo "::group::Versions"

        local_version=${{ steps.local-version.outputs.VERSION }}
        remote_version=${{ steps.remote-version.outputs.VERSION }}

        if [[ ! "${local_version}" =~ $SEMVER_REGEX ]]; then
          echo "::error::Unable to find local version ${local_version}"
          exit 1
        fi

        if [[ ! "${remote_version}" =~ $SEMVER_REGEX ]]; then
          echo "::error::Unable to find remote version ${remote_version}"
          exit 1
        fi

        echo "Project version: ${local_version}"
        echo "Released version: ${remote_version}"
        echo "::endgroup::"

    - name: Publish
      shell: bash
      working_directory: ${{ inputs.working-directory }}
      run: |
        local_version=${{ steps.local-version.outputs.VERSION }}
        remote_version=${{ steps.remote-version.outputs.VERSION }}
        organization=${{ inputs.organization }}

        echo "::group::Publish"

        if [[ "${local_version}" == "${remote_version}" ]]; then
          echo "Version has already been published"
          echo "Doing nothing"
          exit 0
        fi

        if [[ -n "$organization" ]]; then
          mix hex.publish --organization "$organization" --yes
        else
          mix hex.publish --yes
        fi

        echo "::endgroup::"